### ISSUE TITLE
小米手机提取微信聊天记录数据库

### ISSUE THREAD

**Issue by Heyxk** [Heyxk/notes#1]
## 小米 6 提取微信聊天记录笔记
[https://blog.cookbyte.net/post/xiaomi-wechat-history-export/](https://blog.cookbyte.net/post/xiaomi-wechat-history-export/)

**Comment by gitgitss** [comment]
命令行获取的IMEI为null是什么原因呀

**Comment by chshcq** [comment]
我也是有这个null的问题，看了下手机有两个imei，尝试用了第一个imei 加上uid 做一个md5的hash，前七位就是密码

**Comment by yhm2046** [comment]
C:\wechat>java IMEI systemInfo.cfg CompatibleInfo.cfg
错误: 找不到或无法加载主类 IMEI

这个是什么问题？？急求

**Comment by chshcq** [comment]
先不要急，不过我不太了解这个中文错误码对应的英文是什么，应该不是null

**Comment by chshcq** [comment]
你能确认一下你 IMEI.java 健全？

**Comment by yhm2046** [comment]
> 你能确认一下你 IMEI.java 健全？

我试过几次不行就换其他方法了，使用iemi少一位加uin取MD5 加密32位小写前面七位解出了密码：)

**Comment by gitgitss** [comment]
如果他获取的IMEI是null    那他下面算md5就会用null这4个字母

**Comment by linxingwu** [comment]
我和你的完全不一样，我miui 10 开发版，备份出来的bak文件完全就是一个压缩包，可以直接winrar查看，并没有app这个目录，直接就是com.tencent.mm/r，r下面也没有MicroMsg.

**Comment by fly-dragon211** [comment]
您好，运行脚本时我也出现了这个问题：
`
错误: 找不到或无法加载主类 IMEI
原因: java.lang.ClassNotFoundException: IMEI
`

**Comment by yuqyu** [comment]
日消息数走势是怎么分析的呀

**Comment by fly-dragon211** [comment]
> 日消息数走势是怎么分析的呀

这个就是一个统计图，按时间分类就好

**Comment by flylzj** [comment]
我的CompatibleInfo.cfg是空的

**Comment by fly-dragon211** [comment]
> 我的CompatibleInfo.cfg是空的

https://github.com/fly-dragon211/Wechat-message-analysis

**Comment by forconz** [comment]
因为CompatibleInfo.cfg 有可能0字节，所以IMEI.java需要修改下

```
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.security.MessageDigest;
import java.util.HashMap;
import java.io.File;

public class IMEI {
    public static void main(String[] args) {
        try {
            ObjectInputStream in = new ObjectInputStream(new FileInputStream(args[0]));
            Object DL = in.readObject();
            HashMap hashWithOutFormat = (HashMap) DL;

           // CompatibleInfo.cfg 有可能0字节
           String imei = "1234567890ABCDEF"; // 默认字符串
           File fCompatibleInfo = new File(args[1]);
           // 取手机的IMEI
           if(fCompatibleInfo.length() > 0) {
            FileInputStream fisCompatibleInfo = new FileInputStream(fCompatibleInfo);
            ObjectInputStream in1 = new ObjectInputStream(fisCompatibleInfo);
            Object DJ = in1.readObject();            
            HashMap hashWithOutFormat1 = (HashMap) DJ;
            imei = String.valueOf(hashWithOutFormat1.get(Integer.valueOf(258)));
            in1.close();
           }
           System.out.println("The IMEI is : " + imei);

           String uin = String.valueOf(hashWithOutFormat.get(Integer.valueOf(1)));
           System.out.println("The uin is : " + uin);
           imei = imei + uin; //合并到一个字符串
           imei = encode(imei); // hash
           System.out.println("The Key is : " + imei.substring(0, 7));
           in.close();           
        } catch (Exception e) {
            e.printStackTrace();
        }
 }

 public static String encode(String content)
  {
   try {
    MessageDigest digest = MessageDigest.getInstance("MD5");
    digest.update(content.getBytes());
    return getEncode32(digest);
    }
   catch (Exception e)
   {
    e.printStackTrace();
   }
   return null;
  }
  private static String getEncode32(MessageDigest digest)
  {
   StringBuilder builder = new StringBuilder();
   for (byte b : digest.digest())
   {
    builder.append(Integer.toHexString((b >> 4) & 0xf));
    builder.append(Integer.toHexString(b & 0xf));
   }
    return builder.toString(); 
  }
}


```

保存java文件以后
```
> javac IMEI.java
> java IMEI systemInfo.cfg CompatibleInfo.cfg
```
这个java代码中，uin的获取是没问题的。
The uin is :得到的uin和 com.tencent.mm/sp/auth_info_key_prefs.xml 文件里的
`<int name="_auth_uin" value="" /> `
的value值是一样的。

根据uin计算的key，解密数据库实测没有问题。

**Comment by brokendd** [comment]
java纯小白真心提问，出现这个怎么办？？？？
java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
        at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
        at java.io.ObjectInputStream.<init>(Unknown Source)
        at IMEI.main(IMEI.java:12)
